// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MySQLDatabank;

#nullable disable

namespace MySQLDatabank.Migrations
{
    [DbContext(typeof(Databank))]
    partial class DatabankModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GerechtIngredient", b =>
                {
                    b.Property<int>("InGerechtenGerechtId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientenIngredientId")
                        .HasColumnType("int");

                    b.HasKey("InGerechtenGerechtId", "IngredientenIngredientId");

                    b.HasIndex("IngredientenIngredientId");

                    b.ToTable("GerechtIngredient");
                });

            modelBuilder.Entity("GerechtMenu", b =>
                {
                    b.Property<int>("GerechtenGerechtId")
                        .HasColumnType("int");

                    b.Property<int>("InMenusMenuId")
                        .HasColumnType("int");

                    b.HasKey("GerechtenGerechtId", "InMenusMenuId");

                    b.HasIndex("InMenusMenuId");

                    b.ToTable("GerechtMenu");
                });

            modelBuilder.Entity("MyRestaurant_Klassen.Gerecht", b =>
                {
                    b.Property<int>("GerechtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("GerechtId"));

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("Prijs")
                        .HasColumnType("float");

                    b.HasKey("GerechtId");

                    b.ToTable("Gerecht");
                });

            modelBuilder.Entity("MyRestaurant_Klassen.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IngredientId"));

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("PrijsPerKg")
                        .HasColumnType("float");

                    b.HasKey("IngredientId");

                    b.ToTable("Ingredient");
                });

            modelBuilder.Entity("MyRestaurant_Klassen.Menu", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MenuId"));

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("Prijs")
                        .HasColumnType("float");

                    b.HasKey("MenuId");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("GerechtIngredient", b =>
                {
                    b.HasOne("MyRestaurant_Klassen.Gerecht", null)
                        .WithMany()
                        .HasForeignKey("InGerechtenGerechtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyRestaurant_Klassen.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientenIngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GerechtMenu", b =>
                {
                    b.HasOne("MyRestaurant_Klassen.Gerecht", null)
                        .WithMany()
                        .HasForeignKey("GerechtenGerechtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyRestaurant_Klassen.Menu", null)
                        .WithMany()
                        .HasForeignKey("InMenusMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
