// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MySql;

#nullable disable

namespace MySql.Migrations
{
    [DbContext(typeof(Databank))]
    [Migration("20250922081135_afmeting")]
    partial class afmeting
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("_12_1_Classes.Aankoop", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.HasKey("Username", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("Aankoop");
                });

            modelBuilder.Entity("_12_1_Classes.Gebruiker", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Username");

                    b.ToTable("Gebruiker");
                });

            modelBuilder.Entity("_12_1_Classes.Product.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<float?>("Prijs")
                        .HasPrecision(2)
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("_12_1_Classes.Product.Game", b =>
                {
                    b.HasBaseType("_12_1_Classes.Product.Product");

                    b.Property<int>("Console")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.ToTable("Games", (string)null);
                });

            modelBuilder.Entity("_12_1_Classes.Product.Merchandise", b =>
                {
                    b.HasBaseType("_12_1_Classes.Product.Product");

                    b.Property<float>("Gewicht")
                        .HasColumnType("float");

                    b.Property<int>("Soort")
                        .HasColumnType("int");

                    b.ToTable("Merch", (string)null);
                });

            modelBuilder.Entity("_12_1_Classes.Aankoop", b =>
                {
                    b.HasOne("_12_1_Classes.Product.Game", "Game")
                        .WithMany("Licenties")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_12_1_Classes.Gebruiker", "Gebruiker")
                        .WithMany("Aankopen")
                        .HasForeignKey("Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Gebruiker");
                });

            modelBuilder.Entity("_12_1_Classes.Product.Merchandise", b =>
                {
                    b.OwnsOne("_12_1_Classes.Product.Afmeting", "Afmeting", b1 =>
                        {
                            b1.Property<int>("MerchandiseId")
                                .HasColumnType("int");

                            b1.Property<float>("Breedte")
                                .HasColumnType("float");

                            b1.Property<float>("Diepte")
                                .HasColumnType("float");

                            b1.Property<float>("Lengte")
                                .HasColumnType("float");

                            b1.HasKey("MerchandiseId");

                            b1.ToTable("Merch");

                            b1.WithOwner()
                                .HasForeignKey("MerchandiseId");
                        });

                    b.Navigation("Afmeting")
                        .IsRequired();
                });

            modelBuilder.Entity("_12_1_Classes.Gebruiker", b =>
                {
                    b.Navigation("Aankopen");
                });

            modelBuilder.Entity("_12_1_Classes.Product.Game", b =>
                {
                    b.Navigation("Licenties");
                });
#pragma warning restore 612, 618
        }
    }
}
