// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MySql;

#nullable disable

namespace MySql.Migrations
{
    [DbContext(typeof(Databank))]
    partial class DatabankModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Classes.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("GameId"));

                    b.Property<int>("Console")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Prijs")
                        .HasColumnType("double");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("GameId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("_12_1_Classes.Aankoop", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.HasKey("Username", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("Aankoop");
                });

            modelBuilder.Entity("_12_1_Classes.Gebruiker", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Username");

                    b.ToTable("Gebruiker");
                });

            modelBuilder.Entity("_12_1_Classes.Aankoop", b =>
                {
                    b.HasOne("Classes.Game", "Game")
                        .WithMany("Licenties")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_12_1_Classes.Gebruiker", "Gebruiker")
                        .WithMany("Aankopen")
                        .HasForeignKey("Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Gebruiker");
                });

            modelBuilder.Entity("Classes.Game", b =>
                {
                    b.Navigation("Licenties");
                });

            modelBuilder.Entity("_12_1_Classes.Gebruiker", b =>
                {
                    b.Navigation("Aankopen");
                });
#pragma warning restore 612, 618
        }
    }
}
