// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TVSeries_Db;

#nullable disable

namespace TVSeries_Db.Migrations
{
    [DbContext(typeof(Databank))]
    [Migration("20260427130256_start")]
    partial class start
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TVSeries_Db.Aflevering", b =>
                {
                    b.Property<int>("AfleveringId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AfleveringId"));

                    b.Property<float>("Rating")
                        .HasColumnType("float");

                    b.Property<int?>("SeizoenId")
                        .HasColumnType("int");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("AfleveringId");

                    b.HasIndex("SeizoenId");

                    b.ToTable("Aflevering");
                });

            modelBuilder.Entity("TVSeries_Db.Seizoen", b =>
                {
                    b.Property<int>("SeizoenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SeizoenId"));

                    b.Property<int?>("SerieId")
                        .HasColumnType("int");

                    b.Property<int>("Volgnummer")
                        .HasColumnType("int");

                    b.HasKey("SeizoenId");

                    b.HasIndex("SerieId");

                    b.ToTable("Seizoen");
                });

            modelBuilder.Entity("TVSeries_Db.Serie", b =>
                {
                    b.Property<int>("SerieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SerieId"));

                    b.Property<string>("Beschrijving")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("SerieId");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("TVSeries_Db.Aflevering", b =>
                {
                    b.HasOne("TVSeries_Db.Seizoen", null)
                        .WithMany("Afleveringen")
                        .HasForeignKey("SeizoenId");
                });

            modelBuilder.Entity("TVSeries_Db.Seizoen", b =>
                {
                    b.HasOne("TVSeries_Db.Serie", null)
                        .WithMany("Seizoenen")
                        .HasForeignKey("SerieId");
                });

            modelBuilder.Entity("TVSeries_Db.Seizoen", b =>
                {
                    b.Navigation("Afleveringen");
                });

            modelBuilder.Entity("TVSeries_Db.Serie", b =>
                {
                    b.Navigation("Seizoenen");
                });
#pragma warning restore 612, 618
        }
    }
}
