// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Muziekwinkel_databank;

#nullable disable

namespace Muziekwinkel_databank.Migrations
{
    [DbContext(typeof(Databank))]
    [Migration("20260126141645_artiest")]
    partial class artiest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Muziekwinkel_databank.Artiest", b =>
                {
                    b.Property<int>("artiestid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("artiestid"));

                    b.Property<int>("Geboortejaar")
                        .HasColumnType("int");

                    b.Property<bool>("Is_Man")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("artiestid");

                    b.ToTable("Artiesten");
                });
#pragma warning restore 612, 618
        }
    }
}
