// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Muziekwinkel_databank;

#nullable disable

namespace Muziekwinkel_databank.Migrations
{
    [DbContext(typeof(Databank))]
    [Migration("20260127145146_cd")]
    partial class cd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Muziekwinkel_databank.Artiest", b =>
                {
                    b.Property<int>("artiestid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("artiestid"));

                    b.Property<int>("Geboortejaar")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Heeft_Beperking")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Is_Man")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("artiestid");

                    b.ToTable("Artiesten");
                });

            modelBuilder.Entity("Muziekwinkel_databank.CD", b =>
                {
                    b.Property<int>("CDId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CDId"));

                    b.Property<int>("Releasejaar")
                        .HasColumnType("int");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("artiestid")
                        .HasColumnType("int");

                    b.HasKey("CDId");

                    b.HasIndex("artiestid");

                    b.ToTable("CD");
                });

            modelBuilder.Entity("Muziekwinkel_databank.CD", b =>
                {
                    b.HasOne("Muziekwinkel_databank.Artiest", "Artiest")
                        .WithMany("CDs")
                        .HasForeignKey("artiestid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artiest");
                });

            modelBuilder.Entity("Muziekwinkel_databank.Artiest", b =>
                {
                    b.Navigation("CDs");
                });
#pragma warning restore 612, 618
        }
    }
}
