// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyMotorbikeStore_MySQL;

#nullable disable

namespace MyMotorbikeStore_MySQL.Migrations
{
    [DbContext(typeof(MySQLDatabase))]
    [Migration("20260122151223_motorbike_instock")]
    partial class motorbike_instock
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MyMotorbikeStore_classes.Motorbike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CC")
                        .HasColumnType("int");

                    b.Property<float>("Gewicht_kg")
                        .HasColumnType("float");

                    b.Property<int>("InStock")
                        .HasColumnType("int");

                    b.Property<string>("Merk")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("Prijs")
                        .HasColumnType("float");

                    b.Property<DateTime>("Productiedatum")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Motorbikes");
                });
#pragma warning restore 612, 618
        }
    }
}
