// <auto-generated />
using System;
using DB_Strips_Databank;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DB_Strips_Databank.Migrations
{
    [DbContext(typeof(Connectie))]
    [Migration("20260205094334_strips")]
    partial class strips
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DB_Strips_Databank.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TekenaarId")
                        .HasColumnType("int");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("VolgordeNummer")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TekenaarId");

                    b.ToTable("Album");
                });

            modelBuilder.Entity("DB_Strips_Databank.Strip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlbumId")
                        .HasColumnType("int");

                    b.Property<int>("Jaar_druk")
                        .HasColumnType("int");

                    b.Property<float>("Prijs")
                        .HasColumnType("float");

                    b.Property<string>("Staat")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("Strips");
                });

            modelBuilder.Entity("DB_Strips_Databank.Tekenaar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Geboortedatum")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Tekenaar");
                });

            modelBuilder.Entity("DB_Strips_Databank.Album", b =>
                {
                    b.HasOne("DB_Strips_Databank.Tekenaar", "Tekenaar")
                        .WithMany("Albums")
                        .HasForeignKey("TekenaarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tekenaar");
                });

            modelBuilder.Entity("DB_Strips_Databank.Strip", b =>
                {
                    b.HasOne("DB_Strips_Databank.Album", "Album")
                        .WithMany("Exemplaren")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("DB_Strips_Databank.Album", b =>
                {
                    b.Navigation("Exemplaren");
                });

            modelBuilder.Entity("DB_Strips_Databank.Tekenaar", b =>
                {
                    b.Navigation("Albums");
                });
#pragma warning restore 612, 618
        }
    }
}
