// <auto-generated />
using CRUD_Gezelschapsspelletjes;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRUD_Gezelschapsspelletjes.Migrations
{
    [DbContext(typeof(Connectie))]
    partial class ConnectieModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CRUD_Gezelschapsspelletjes.Gezelschapsspel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Beschrijving")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Maximum_Spelers")
                        .HasColumnType("int");

                    b.Property<int>("Minimum_Spelers")
                        .HasColumnType("int");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("WerktOpBatterijen")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Gezelschapsspelletjes");
                });
#pragma warning restore 612, 618
        }
    }
}
