// <auto-generated />
using Databank;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Databank.Migrations
{
    [DbContext(typeof(MySQLDatabank))]
    partial class MySQLDatabankModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("LessEpicGames_Klassen.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Moeilijkheidsgraad_op_10")
                        .HasColumnType("int");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("VideogameId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VideogameId");

                    b.ToTable("Achievement");
                });

            modelBuilder.Entity("LessEpicGames_Klassen.Ontwikkelaar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres_HQ")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CEO")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Oprichtingsjaar")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Ontwikkelaar");
                });

            modelBuilder.Entity("LessEpicGames_Klassen.Videogame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("GemiddeldSpeeltijd_Uur")
                        .HasColumnType("double");

                    b.Property<double>("Prijs")
                        .HasColumnType("double");

                    b.Property<int>("Releasejaar")
                        .HasColumnType("int");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Videogames");
                });

            modelBuilder.Entity("OntwikkelaarVideogame", b =>
                {
                    b.Property<int>("OntwikkelaarsId")
                        .HasColumnType("int");

                    b.Property<int>("VideogamesId")
                        .HasColumnType("int");

                    b.HasKey("OntwikkelaarsId", "VideogamesId");

                    b.HasIndex("VideogamesId");

                    b.ToTable("OntwikkelaarVideogame");
                });

            modelBuilder.Entity("LessEpicGames_Klassen.Achievement", b =>
                {
                    b.HasOne("LessEpicGames_Klassen.Videogame", null)
                        .WithMany("Achievements")
                        .HasForeignKey("VideogameId");
                });

            modelBuilder.Entity("OntwikkelaarVideogame", b =>
                {
                    b.HasOne("LessEpicGames_Klassen.Ontwikkelaar", null)
                        .WithMany()
                        .HasForeignKey("OntwikkelaarsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LessEpicGames_Klassen.Videogame", null)
                        .WithMany()
                        .HasForeignKey("VideogamesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LessEpicGames_Klassen.Videogame", b =>
                {
                    b.Navigation("Achievements");
                });
#pragma warning restore 612, 618
        }
    }
}
