// <auto-generated />
using System;
using DB_School_Databank;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DB_School_Databank.Migrations
{
    [DbContext(typeof(Connectie))]
    [Migration("20260129091007_klassen")]
    partial class klassen
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DB_School_Databank.Klas", b =>
                {
                    b.Property<string>("Naam")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Naam");

                    b.ToTable("Klassen");
                });

            modelBuilder.Entity("DB_School_Databank.Leerling", b =>
                {
                    b.Property<int>("LeerlingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LeerlingId"));

                    b.Property<DateTime>("Geboortedatum")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("KlasNaam")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Last name");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("First name");

                    b.HasKey("LeerlingId");

                    b.HasIndex("KlasNaam");

                    b.ToTable("Leerlingen");
                });

            modelBuilder.Entity("DB_School_Databank.Leerling", b =>
                {
                    b.HasOne("DB_School_Databank.Klas", "Klas")
                        .WithMany("Leerling")
                        .HasForeignKey("KlasNaam")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Klas");
                });

            modelBuilder.Entity("DB_School_Databank.Klas", b =>
                {
                    b.Navigation("Leerling");
                });
#pragma warning restore 612, 618
        }
    }
}
